Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2018-10, with the labels that each got.

#2 Dangerfinder
  CMakeLists.txt
  roboteam_ai/src/DangerFinder/DangerData.cpp
  roboteam_ai/src/DangerFinder/DangerData.h
  roboteam_ai/src/DangerFinder/DangerFinder.cpp
  roboteam_ai/src/DangerFinder/DangerFinder.h
  roboteam_ai/src/DangerFinder/DangerFinderConfig.cpp
  roboteam_ai/src/DangerFinder/DangerFinderConfig.h
  roboteam_ai/src/DangerFinder/PartialResult.cpp
  roboteam_ai/src/DangerFinder/PartialResult.h
  roboteam_ai/src/DangerFinder/modules/CanShootModule.cpp
  roboteam_ai/src/DangerFinder/modules/CanShootModule.h
  roboteam_ai/src/DangerFinder/modules/DangerModule.cpp
  roboteam_ai/src/DangerFinder/modules/DangerModule.h
  roboteam_ai/src/DangerFinder/modules/DistanceModule.cpp
  roboteam_ai/src/DangerFinder/modules/DistanceModule.h
  roboteam_ai/src/DangerFinder/modules/FreeModule.cpp
  roboteam_ai/src/DangerFinder/modules/FreeModule.h
  roboteam_ai/src/DangerFinder/modules/HasBallModule.cpp
  roboteam_ai/src/DangerFinder/modules/HasBallModule.h
  roboteam_ai/src/DangerFinder/modules/OrientationModule.cpp
  roboteam_ai/src/DangerFinder/modules/OrientationModule.h
  roboteam_ai/src/DangerFinder/modules/WillReceiveBallModule.cpp
  roboteam_ai/src/DangerFinder/modules/WillReceiveBallModule.h
  roboteam_ai/src/StrategyNode.cpp
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/io/IOManager.h
  roboteam_ai/src/io/RoleIOManager.cpp
  roboteam_ai/src/io/StrategyIOManager.cpp
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
  roboteam_ai/test/DangerFinderTest.cpp
  roboteam_ai/test/SimpleTest.cpp
  roboteam_ai/test/WorldTest.cpp
Labels: feature

#8 Add more dangerfinder tests
  roboteam_ai/src/DangerFinder/DangerFinder.cpp
  roboteam_ai/test/DangerFinderTest.cpp
Labels: enhancement

#12 Feature/coverage
  CMakeLists.txt
  cmake_modules/CodeCoverage.cmake
  roboteam_ai/src/DangerFinder/DangerFinder.cpp
  roboteam_ai/src/bt/Blackboard.cpp
  roboteam_ai/src/bt/Blackboard.hpp
  roboteam_ai/src/bt/Composite.cpp
  roboteam_ai/src/bt/Composite.hpp
  roboteam_ai/src/bt/Node.cpp
  roboteam_ai/src/bt/composites/MemSelector.cpp
  roboteam_ai/src/bt/composites/MemSelector.hpp
  roboteam_ai/src/bt/composites/MemSequence.cpp
  roboteam_ai/src/bt/composites/MemSequence.hpp
  roboteam_ai/src/bt/composites/ParallelSequence.cpp
  roboteam_ai/src/bt/composites/ParallelSequence.hpp
  roboteam_ai/src/bt/composites/Selector.cpp
  roboteam_ai/src/bt/composites/Selector.hpp
  roboteam_ai/src/bt/composites/Sequence.cpp
  roboteam_ai/src/bt/composites/Sequence.hpp
  roboteam_ai/test/BTBlackBoardTest.cpp
  roboteam_ai/test/BtTest.cpp
  roboteam_ai/test/DangerFinderTest.cpp
Labels: Work in progress

#18 Feature/robotdealer
  CMakeLists.txt
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/RobotDealer.h
  roboteam_ai/test/RobotDealerTest.cpp
Labels: feature
