Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-04, with the labels that each got.

#221 Feature/keepervisualization
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/bt/Composite.cpp
  roboteam_ai/src/bt/Role.cpp
  roboteam_ai/src/bt/Role.h
  roboteam_ai/src/bt/tactics/AvoidBallTactic.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/PathPoint.cpp
  roboteam_ai/src/interface/TreeVisualizerWidget.cpp
  roboteam_ai/src/interface/TreeVisualizerWidget.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/jsons/keeper/Keeper.json
  roboteam_ai/src/jsons/keeper/SingleKeeperTactic.json
  roboteam_ai/src/jsons/roles/DefenderRole.json
  roboteam_ai/src/jsons/strategies/DemoTeamTwenteStrategy.json
  roboteam_ai/src/jsons/strategies/EnterFormationStrategy.json
  roboteam_ai/src/jsons/strategies/threePlayerStrategyV2.json
  roboteam_ai/src/jsons/strategies/twoPlayerStrategyV2.json
  roboteam_ai/src/jsons/tactics/DemoTactic.json
  roboteam_ai/src/skills/EnterFormation.cpp
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/treeinterp/BTFactory.h
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/RobotDealer.h
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
  roboteam_ai/test/SkillTests/DefendTest.cpp
  roboteam_ai/test/SkillTests/FormationTest.cpp
  roboteam_ai/test/SkillTests/GoToPosTest.cpp
  roboteam_ai/test/SkillTests/KickTest.cpp
  roboteam_ai/test/TacticTests/DefaultTacticTest.cpp
  roboteam_ai/test/TreeInterpreterTests/BtTest.cpp
  roboteam_ai/test/UtilTests/RobotDealerTest.cpp
  roboteam_ai/test/main.cpp
Labels: Critical priority, Work in progress

#241 fix integer divsion in game analyzer
  roboteam_ai/src/analysis/GameAnalyzer.cpp
Labels: Low priority

#240 make the avoiders more awesome and do ballplacement from the sides
  roboteam_ai/src/jsons/roles/BallPlacementPasser.json
  roboteam_ai/src/jsons/tactics/AvoidBallTactic.json
  roboteam_ai/src/jsons/tactics/BallPlacementDoubleTactic.json
  roboteam_ai/src/skills/AvoidBall.cpp
Labels: Low priority, feature

#250 Feature/more pids interface
  CMakeLists.txt
  roboteam_ai/src/control/pid.cpp
  roboteam_ai/src/control/pid.h
  roboteam_ai/src/control/positionControllers/BasicPosControl.cpp
  roboteam_ai/src/control/positionControllers/BasicPosControl.h
  roboteam_ai/src/control/positionControllers/ControlGoToPosBallControl.cpp
  roboteam_ai/src/control/positionControllers/ControlGoToPosBallControl.h
  roboteam_ai/src/control/positionControllers/ForcePosControl.cpp
  roboteam_ai/src/control/positionControllers/ForcePosControl.h
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.h
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/control/positionControllers/PosController.h
  roboteam_ai/src/interface/InterfaceValues.cpp
  roboteam_ai/src/interface/InterfaceValues.h
  roboteam_ai/src/interface/PidBox.cpp
  roboteam_ai/src/interface/PidBox.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/InterfaceTests/InterfaceTest.cpp
Labels: Ready for review

#235 Feature/offensive positioning
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/coach/CoachHeuristics.cpp
  roboteam_ai/src/coach/CoachHeuristics.h
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/OffensiveCoach.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/interface/drawer.cpp
  roboteam_ai/src/interface/drawer.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/jsons/tactics/SideAttackerTactic.json
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/SideAttacker.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/test/CoachTests/OffensiveCoachTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/UtilTests/WorldTest.cpp
Labels: Ready for review

#251 Feature/acceleration limiter
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/control/positionControllers/PosController.h
  roboteam_ai/src/jsons/keeper/Keeper.json
  roboteam_ai/src/skills/Defend.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
Labels: Ready for review, feature

#252 Feature/better defenders
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/defence/DefenceDealer.cpp
  roboteam_ai/src/coach/defence/DefenceDealer.h
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.h
  roboteam_ai/src/coach/defence/PossiblePass.cpp
  roboteam_ai/src/coach/defence/PossiblePass.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/interface/drawer.cpp
  roboteam_ai/src/interface/drawer.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
  roboteam_ai/src/jsons/keeper/keeperTest1.json
  roboteam_ai/src/jsons/roles/coachDefender.json
  roboteam_ai/src/jsons/strategies/coachDefenderStrategy.json
  roboteam_ai/src/jsons/tactics/coachDefenderTactic.json
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/skills/CoachDefend.h
  roboteam_ai/src/skills/Halt.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/src/world/Field.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
  roboteam_ai/test/CoachTests/DefensiveCoachTest.cpp
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
  roboteam_ai/test/UtilTests/FieldTest.cpp
  roboteam_ai/test/UtilTests/OffensiveCoachTest.cpp
Labels: Ready for merge

#265 Bugfix/fix major issues
  launch/two-teams.launch
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/bt/Leaf.cpp
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/test/SkillTests/KickTest.cpp
  roboteam_ai/test/UtilTests/IOTest.cpp
Labels: Critical priority

#267 Interface upgrades
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
Labels: Ready for review, feature

#270 Feature/geneva interface
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
Labels: Ready for review, enhancement

#261 Refactor/normal gtp intercept
  CMakeLists.txt
  roboteam_ai/src/control/PIDController.cpp
  roboteam_ai/src/control/PIDController.h
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/test/ControlTests/ControllerTest.cpp
Labels: Ready for review, refactor

#271 Feature/receive to kick
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/CoachHeuristics.cpp
  roboteam_ai/src/coach/CoachHeuristics.h
  roboteam_ai/src/coach/GeneralPositionCoach.cpp
  roboteam_ai/src/coach/GeneralPositionCoach.h
  roboteam_ai/src/jsons/roles/MidFielder.json
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/tactics/PassAndShootTactic.json
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/GTPSpecial.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Reflect.cpp
  roboteam_ai/src/skills/Reflect.h
  roboteam_ai/src/skills/ReflectKick.cpp
  roboteam_ai/src/skills/ReflectKick.h
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/Hungarian.cpp
  roboteam_ai/src/world/Robot.h
Labels: Ready for review

#285 Feature/ball possession
  CMakeLists.txt
  roboteam_ai/src/analysis/GameAnalyzer.cpp
  roboteam_ai/src/analysis/GameAnalyzer.h
  roboteam_ai/src/jsons/tactics/oner_robot_ballplacement_tactic.json
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/src/world/BallPossession.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
Labels: Ready for review

#279 Refactor/clean conditions
  roboteam_ai/src/conditions/BallInDefenseAreaAndStill.cpp
  roboteam_ai/src/conditions/BallInDefenseAreaAndStill.h
  roboteam_ai/src/conditions/BallKickedToOurGoal.cpp
  roboteam_ai/src/conditions/BallKickedToOurGoal.h
  roboteam_ai/src/conditions/BallNearOurGoalLineAndStill.cpp
  roboteam_ai/src/conditions/BallNearOurGoalLineAndStill.h
  roboteam_ai/src/conditions/BallOutOfField.cpp
  roboteam_ai/src/conditions/BallOutOfField.h
  roboteam_ai/src/conditions/HasBall.hpp
  roboteam_ai/src/conditions/HasClearShot.cpp
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/conditions/IsBallCloseToBorder.cpp
  roboteam_ai/src/conditions/IsBallCloseToBorder.h
  roboteam_ai/src/conditions/IsBallOnOurSide.cpp
  roboteam_ai/src/conditions/IsBallOnOurSide.h
  roboteam_ai/src/conditions/IsBeingPassedTo.cpp
  roboteam_ai/src/conditions/IsBeingPassedTo.h
  roboteam_ai/src/conditions/IsCloseToPoint.cpp
  roboteam_ai/src/conditions/IsCloseToPoint.h
  roboteam_ai/src/conditions/IsInDefenseArea.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.hpp
  roboteam_ai/src/conditions/IsRobotClosestToBall.cpp
  roboteam_ai/src/conditions/IsRobotClosestToBall.h
  roboteam_ai/src/conditions/TheyHaveBall.cpp
  roboteam_ai/src/conditions/TheyHaveBall.h
  roboteam_ai/src/conditions/TwoRobotBallPlacement.cpp
  roboteam_ai/src/conditions/TwoRobotBallPlacement.h
  roboteam_ai/src/conditions/WeHaveBall.cpp
  roboteam_ai/src/conditions/WeHaveBall.h
  roboteam_ai/test/ConditionTests/BallInDefenseAreaAndStillTest.cpp
  roboteam_ai/test/ConditionTests/BallKickedToOurGoalTest.cpp
  roboteam_ai/test/ConditionTests/BallOutOfFieldtest.cpp
  roboteam_ai/test/ConditionTests/HasBallTest.cpp
  roboteam_ai/test/ConditionTests/IsBallOnOurSideTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
  roboteam_ai/test/ConditionTests/TheyHaveBallTest.cpp
  roboteam_ai/test/ConditionTests/WeHaveBallTest.cpp
Labels: Low priority, Ready for merge, refactor

#284 Feature/better passing logic
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/CoachHeuristics.cpp
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/OffensiveCoach.h
  roboteam_ai/src/coach/PassCoach.cpp
  roboteam_ai/src/coach/PassCoach.h
  roboteam_ai/src/coach/heurstics/CoachHeuristics.cpp
  roboteam_ai/src/coach/heurstics/CoachHeuristics.h
  roboteam_ai/src/coach/heurstics/OffensiveScore.cpp
  roboteam_ai/src/coach/heurstics/OffensiveScore.h
  roboteam_ai/src/coach/heurstics/PassScore.cpp
  roboteam_ai/src/coach/heurstics/PassScore.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/jsons/roles/PassRole.json
  roboteam_ai/src/jsons/roles/test_receive_role.json
  roboteam_ai/src/jsons/strategies/test_pass_strategy.json
  roboteam_ai/src/jsons/tactics/test_pass_tactic.json
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/treeinterp/config_files/other.csv
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/test/CoachTests/OffensiveCoachTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/helpers/FieldHelper.cpp
  roboteam_ai/test/helpers/FieldHelper.h
Labels: Ready for review

#291 Hotfix/ball existence
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/analysis/GameAnalyzer.cpp
  roboteam_ai/src/bt/RoleDivider.cpp
  roboteam_ai/src/bt/RoleDivider.h
  roboteam_ai/src/bt/tactics/DefaultTactic.cpp
  roboteam_ai/src/bt/tactics/DefaultTactic.h
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/PosVelAngle.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Defend.cpp
  roboteam_ai/src/skills/ShootFreeKick.cpp
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/formations/Formation.cpp
  roboteam_ai/src/skills/formations/KickOffThemFormation.cpp
  roboteam_ai/src/skills/formations/KickOffUsFormation.cpp
  roboteam_ai/src/utilities/Hungarian.cpp
  roboteam_ai/src/world/Ball.cpp
  roboteam_ai/src/world/Ball.h
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/src/world/History.cpp
  roboteam_ai/src/world/History.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
  roboteam_ai/test/CoachTests/OffensiveCoachTest.cpp
  roboteam_ai/test/ConditionTests/HasBallTest.cpp
  roboteam_ai/test/ConditionTests/IsBallOnOurSideTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
  roboteam_ai/test/InterfaceTests/MainWindowTest.cpp
  roboteam_ai/test/SkillTests/DefendTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/UtilTests/FieldTest.cpp
  roboteam_ai/test/helpers/WorldHelper.cpp
  roboteam_ai/test/roboteam_utils_Tests/AngleTest.cpp
Labels: Ready for review

#288 add some critical tests: world state, playstyles, defaultTactic
  CMakeLists.txt
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/analysis/DecisionMaker.h
  roboteam_ai/src/analysis/GameAnalyzer.h
  roboteam_ai/src/bt/Tactic.h
  roboteam_ai/src/bt/tactics/DefaultTactic.cpp
  roboteam_ai/src/bt/tactics/DefaultTactic.h
  roboteam_ai/src/skills/formations/KickOffThemFormation.cpp
  roboteam_ai/src/skills/formations/KickOffUsFormation.cpp
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/test/AnalysisTests/DecisionmakerTest.cpp
  roboteam_ai/test/ConditionTests/HasBallTest.cpp
  roboteam_ai/test/TacticTests/DefaultTacticTest.cpp
  roboteam_ai/test/UtilTests/RobotDealerTest.cpp
  roboteam_ai/test/UtilTests/WorldTest.cpp
  roboteam_ai/test/WorldTests/FieldTest.cpp
  roboteam_ai/test/WorldTests/WorldManagerTest.cpp
  roboteam_ai/test/WorldTests/WorldTest.cpp
Labels: Ready for review

#297 Hotfix/interface inversion keeper
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/interface/widget.cpp
Labels: enhancement

#295 Fix some minor issues: robot id -1 and breaking jsons
  roboteam_ai/src/conditions/Condition.cpp
  roboteam_ai/src/jsons/roles/DemoAttackerRole.json
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/test/ConditionTests/HasBallTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
Labels: Ready for review

#300 fix switches claiming
  roboteam_ai/src/Switches.cpp
Labels: Ready for merge

#277 Feature/defenders pass
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/GetBallCoach.cpp
  roboteam_ai/src/coach/GetBallCoach.h
  roboteam_ai/src/coach/defence/DefenceDealer.cpp
  roboteam_ai/src/coach/defence/DefenceDealer.h
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/conditions/ShouldHandleBall.cpp
  roboteam_ai/src/conditions/ShouldHandleBall.h
  roboteam_ai/src/jsons/roles/coachDefender.json
  roboteam_ai/src/jsons/tactics/TestD.json
  roboteam_ai/src/jsons/tactics/coachDefenderTactic.json
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/world/Ball.cpp
Labels: Ready for review

#313 Hotfix/pidvalues (basic GTP speed fix)
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/utilities/Constants.h
Labels: Ready for merge

#312 fix hungarian
  roboteam_ai/src/utilities/Hungarian.cpp
Labels: Ready for merge

#314 Feature/initialize-pass-later
  roboteam_ai/src/jsons/roles/test_receive_role.json
  roboteam_ai/src/jsons/tactics/test_pass_tactic.json
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/Receive.cpp
Labels: Work in progress

#310 PenaltyKeeper Skill
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/keeper/keeper_penalty_tactic.json
  roboteam_ai/src/jsons/roles/penaltyKeeperRole.json
  roboteam_ai/src/skills/PenaltyKeeper.cpp
  roboteam_ai/src/skills/PenaltyKeeper.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Constants.h
Labels: Ready for review, feature, high priority

#272 Make SlingShot skill
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/roles/SlingshotBot.json
  roboteam_ai/src/jsons/strategies/SlingShotStrategy.json
  roboteam_ai/src/jsons/tactics/SlingShotTactic.json
  roboteam_ai/src/skills/SlingShot.cpp
  roboteam_ai/src/skills/SlingShot.h
Labels: Ready for merge

#286 Feature/defenders fixes
  roboteam_ai/src/coach/defence/DefenceDealer.h
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.h
  roboteam_ai/src/coach/defence/PossiblePass.cpp
  roboteam_ai/src/coach/defence/PossiblePass.h
Labels: Ready for review

#320 remove defendonrobot
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/skills/DefendOnRobot.cpp
  roboteam_ai/src/skills/DefendOnRobot.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/test/SkillTests/DefendOnRobotTest.cpp
Labels: refactor

#331 make sure ros is properly used in world
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/world/WorldManager.cpp
  roboteam_ai/src/world/WorldManager.h
Labels: Ready for review, refactor

#304 Feature/better kickoff
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/analysis/DecisionMaker.h
  roboteam_ai/src/bt/tactics/DefaultTactic.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/jsons/roles/kickoff_kicker_role.json
  roboteam_ai/src/jsons/strategies/kickoff_shoot_strategy.json
  roboteam_ai/src/jsons/tactics/kickoff_shoot_tactic.json
  roboteam_ai/src/skills/formations/KickOffThemFormation.cpp
  roboteam_ai/src/skills/formations/KickOffUsFormation.cpp
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/StrategyManager.cpp
  roboteam_ai/src/utilities/StrategyManager.h
  roboteam_ai/src/world/WorldManager.cpp
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
Labels: Ready for merge

#339 fixes receiver oscillation.
  roboteam_ai/src/skills/Receive.cpp
Labels: Quick fix, Ready for merge, Ready for review

#274 Feature/mid fielders
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/OffensiveCoach.h
  roboteam_ai/src/coach/PassCoach.cpp
  roboteam_ai/src/coach/PassCoach.h
  roboteam_ai/src/coach/heuristics/CoachHeuristics.cpp
  roboteam_ai/src/coach/heuristics/CoachHeuristics.h
  roboteam_ai/src/coach/midField/HarassRobotCoach.cpp
  roboteam_ai/src/coach/midField/HarassRobotCoach.h
  roboteam_ai/src/conditions/HasClearShot.cpp
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/jsons/roles/MidFieldHarassRole.json
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/roles/coachDefender.json
  roboteam_ai/src/jsons/strategies/MidFieldHarassStrategy.json
  roboteam_ai/src/jsons/tactics/MidFieldHarassTactic.json
  roboteam_ai/src/jsons/tactics/TestD.json
  roboteam_ai/src/jsons/tactics/TestM.json
  roboteam_ai/src/jsons/tactics/TestO.json
  roboteam_ai/src/jsons/tactics/kickoff_them_formation_tactic.json
  roboteam_ai/src/jsons/tactics/kickoff_us_tactic.json
  roboteam_ai/src/skills/Halt.cpp
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/MidFieldHarasser.h
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/SideAttacker.h
  roboteam_ai/src/skills/SkillGoToPos.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/world/World.cpp
Labels: Ready for review

#344 Feature/only shoot when can
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/tactics/TestO.json
Labels: Work in progress

#318 shotcontroller
  CMakeLists.txt
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/coach/GeneralPositionCoach.h
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/PositionUtils.cpp
  roboteam_ai/src/control/PositionUtils.h
  roboteam_ai/src/control/positionControllers/BasicPosControl.cpp
  roboteam_ai/src/control/positionControllers/PosVelAngle.h
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/control/shotControllers/ShotData.h
  roboteam_ai/src/skills/ActiveStop.cpp
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Attack.h
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/skills/TurnGeneva.cpp
  roboteam_ai/src/skills/TurnGeneva.h
  roboteam_ai/src/skills/formations/DefendFreeKick.cpp
  roboteam_ai/src/skills/formations/DefendFreeKick.h
  roboteam_ai/src/skills/formations/FreeKickFormation.cpp
  roboteam_ai/src/skills/formations/FreeKickFormation.h
  roboteam_ai/src/skills/formations/PenaltyFormation.cpp
  roboteam_ai/src/skills/formations/PenaltyFormation.h
  roboteam_ai/src/skills/gotopos/GTPSpecial.h
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/test/ControlTests/PositionUtilsTest.cpp
  roboteam_ai/test/ControlTests/ShotControllerTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
Labels: Ready for review, refactor

#340 Feature/auto tree switch
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/conditions/BallIsMoving.cpp
  roboteam_ai/src/conditions/BallIsMoving.h
  roboteam_ai/src/jsons/strategies/kickoff_shoot_strategy.json
  roboteam_ai/src/jsons/strategies/kickoff_us_formation_strategy.json
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/utilities/StrategyManager.cpp
  roboteam_ai/src/utilities/StrategyManager.h
Labels: Ready for merge

#360 fix strategymanager test
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
Labels: Ready for merge

#337 fixPenaltyKeeper
  roboteam_ai/src/skills/PenaltyKeeper.cpp
  roboteam_ai/src/skills/PenaltyKeeper.h
  roboteam_ai/src/utilities/Constants.h
Labels: Quick fix, Ready for merge

#361 make sure shotcontroller kicks
  roboteam_ai/src/control/shotControllers/ShotController.cpp
Labels: Ready for merge

#350 Add DistanceToBallScore
  roboteam_ai/src/coach/heuristics/CoachHeuristics.cpp
  roboteam_ai/src/coach/heuristics/CoachHeuristics.h
  roboteam_ai/src/coach/heuristics/PassScore.cpp
  roboteam_ai/src/coach/heuristics/PassScore.h
  roboteam_ai/test/SkillTests/PassTest.cpp
Labels: Ready for merge

#368 Feature/robots without geneva
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
Labels: Ready for merge

#370 Improve avoiding ball
  roboteam_ai/src/conditions/IsOnPassLine.cpp
  roboteam_ai/src/conditions/IsOnPassLine.h
Labels: Ready for merge

#371 catch ball on side of kicker + don't allow changing geneva while it still turns
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
Labels: Ready for merge

#380 Hotfix/minor fixes
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/strategies/DemoStrategy.json
  roboteam_ai/src/jsons/strategies/DemoTeamTwenteStrategy.json
  roboteam_ai/src/jsons/strategies/EnterFormationStrategy.json
  roboteam_ai/src/jsons/strategies/FreeKickShootStrategy.json
  roboteam_ai/src/jsons/strategies/InterceptRobotTestStrategy.json
  roboteam_ai/src/jsons/strategies/MidFieldHarassStrategy.json
  roboteam_ai/src/jsons/strategies/OffenseStrategy.json
  roboteam_ai/src/jsons/strategies/PassAndShootStrategy.json
  roboteam_ai/src/jsons/strategies/PassStrategy.json
  roboteam_ai/src/jsons/strategies/PenaltyAtackStrategy.json
  roboteam_ai/src/jsons/strategies/PenaltyShootStrategy.json
  roboteam_ai/src/jsons/strategies/PenaltyStrategy.json
  roboteam_ai/src/jsons/strategies/QualificationStrategy.json
  roboteam_ai/src/jsons/strategies/SideAttackerStrategy.json
  roboteam_ai/src/jsons/strategies/SlingShotStrategy.json
  roboteam_ai/src/jsons/strategies/TimeOutFormationStrategy.json
  roboteam_ai/src/jsons/strategies/coachDefenderStrategy.json
  roboteam_ai/src/jsons/strategies/kickoff_them_formation_strategy.json
  roboteam_ai/src/jsons/strategies/kickoff_them_strategy.json
  roboteam_ai/src/jsons/strategies/kickoff_us_formation_strategy.json
  roboteam_ai/src/jsons/strategies/normal_play_strategy.json
  roboteam_ai/src/jsons/strategies/penalty_us_prepare_strategy.json
  roboteam_ai/src/jsons/strategies/penalty_us_shoot_strategy.json
  roboteam_ai/src/jsons/tactics/AvoidBallTactic.json
  roboteam_ai/src/jsons/tactics/BallPlacementDoubleTactic.json
  roboteam_ai/src/jsons/tactics/BallPlacementUsTactic.json
  roboteam_ai/src/jsons/tactics/DemoAttackerTactic.json
  roboteam_ai/src/jsons/tactics/DemoTactic.json
  roboteam_ai/src/jsons/tactics/EnterFormationTactic.json
  roboteam_ai/src/jsons/tactics/GetBallTestTactic.json
  roboteam_ai/src/jsons/tactics/InterceptRobotTestTactic.json
  roboteam_ai/src/jsons/tactics/PassAndShootTactic.json
  roboteam_ai/src/jsons/tactics/PassTactic.json
  roboteam_ai/src/jsons/tactics/SlingShotTactic.json
  roboteam_ai/src/jsons/tactics/TestD.json
  roboteam_ai/src/jsons/tactics/TestM.json
  roboteam_ai/src/jsons/tactics/TestO.json
  roboteam_ai/src/jsons/tactics/TimeOutTactic.json
  roboteam_ai/src/jsons/tactics/coachDefenderTactic.json
  roboteam_ai/src/jsons/tactics/grsimTestTactic.json
  roboteam_ai/src/jsons/tactics/kickoff_them_tactic.json
  roboteam_ai/src/jsons/tactics/kickoff_us_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_defense_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_midfield_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_offense_tactic.json
  roboteam_ai/src/jsons/tactics/oner_robot_ballplacement_tactic.json
  roboteam_ai/src/jsons/tactics/randomTactic.json
  roboteam_ai/src/utilities/StrategyManager.h
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
Labels: Ready for merge

#381 Feature/defenders too far forwards
  roboteam_ai/src/coach/GetBallCoach.cpp
  roboteam_ai/src/coach/defence/DefenceDealer.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.h
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/src/world/Field.h
Labels: Ready for review

#387 Small segfault prevention
  roboteam_ai/src/skills/MidFieldHarasser.cpp
Labels: Quick fix, Ready for review

#389 fix referee segfault for penalties us
  roboteam_ai/src/utilities/StrategyManager.h
Labels: Ready for merge
