Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-02, with the labels that each got.

#113 Avoidance using forces
  CMakeLists.txt
  launch/two-teams-serial.launch
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/bt/Leaf.cpp
  roboteam_ai/src/bt/tactics/AvoidBallTactic.cpp
  roboteam_ai/src/bt/tactics/AvoidBallTactic.h
  roboteam_ai/src/conditions/BallOutOfField.cpp
  roboteam_ai/src/conditions/BallOutOfField.h
  roboteam_ai/src/conditions/HasBall.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.cpp
  roboteam_ai/src/interface/InterfaceValues.cpp
  roboteam_ai/src/interface/InterfaceValues.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/jsons/strategies/BallPlacementThemStrategy.json
  roboteam_ai/src/jsons/strategies/BallPlacementUsStrategy.json
  roboteam_ai/src/jsons/tactics/AvoidBallForBallPlacementTactic.json
  roboteam_ai/src/jsons/tactics/AvoidBallTactic.json
  roboteam_ai/src/jsons/tactics/SingleKeeperTactic.json
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/AvoidBall.cpp
  roboteam_ai/src/skills/AvoidBall.h
  roboteam_ai/src/skills/AvoidBallForBallPlacement.cpp
  roboteam_ai/src/skills/EnterFormation.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/StrategyManager.h
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
  roboteam_ai/test/UtilTests/IOTest.cpp
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
Labels: Ready for merge

#125 Feature/utilities tests
  CMakeLists.txt
  roboteam_ai/src/skills/BasicGoToPos.cpp
  roboteam_ai/src/utilities/Coach.cpp
  roboteam_ai/src/utilities/Coach.h
  roboteam_ai/src/utilities/Field.cpp
  roboteam_ai/test/ApplicationManagerTest.cpp
  roboteam_ai/test/UtilTests/CoachTest.cpp
  roboteam_ai/test/UtilTests/FieldTest.cpp
Labels: Ready for review

#121 Go Around Pos
  CMakeLists.txt
  roboteam_ai/src/bt/Node.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/skills/GoAroundPos.cpp
  roboteam_ai/src/skills/GoAroundPos.h
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Constants.h
Labels: Ready for merge, Ready for review, feature

#128 Interface tests
  CMakeLists.txt
  roboteam_ai/src/interface/RobotsWidget.cpp
  roboteam_ai/src/interface/RobotsWidget.h
  roboteam_ai/src/interface/TreeVisualizerWidget.cpp
  roboteam_ai/src/interface/TreeVisualizerWidget.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/test/InterfaceTests/MainWindowTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
Labels: Ready for review

#131 fix #70
  roboteam_ai/src/bt/composites/MemSelector.hpp
  roboteam_ai/test/TreeInterpreterTests/BtTest.cpp
Labels: Ready for review

#135 Give Roboteam AI the glory it deserves!
  roboteam_ai/src/bt/Node.cpp
  roboteam_ai/src/bt/Node.hpp
  roboteam_ai/src/interface/RobotsWidget.cpp
  roboteam_ai/src/interface/RobotsWidget.h
  roboteam_ai/src/interface/TreeVisualizerWidget.cpp
  roboteam_ai/src/interface/TreeVisualizerWidget.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/roboteam_ai.cpp
  roboteam_ai/test/InterfaceTests/MainWindowTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
Labels: Critical priority, Ready for review

#134 Goal visibility calculations
  roboteam_ai/src/utilities/Field.cpp
  roboteam_ai/src/utilities/Field.h
  roboteam_ai/test/UtilTests/FieldTest.cpp
Labels: Ready for review

#137 Hotfix/robot vis segfault
  roboteam_ai/src/interface/RobotsWidget.cpp
Labels: Critical priority, Ready for review, bug

#140 Use the hungarian algorithm to make robots drive to locations nicely
  CMakeLists.txt
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/utilities/Coach.cpp
  roboteam_ai/src/utilities/Hungarian.cpp
  roboteam_ai/src/utilities/Hungarian.h
  roboteam_ai/test/UtilTests/CoachTest.cpp
  roboteam_ai/test/UtilTests/HungarianTest.cpp
Labels: Ready for review

#141 Feature/pause and Demo Joystick
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/demo/JoystickDemo.cpp
  roboteam_ai/src/demo/JoystickDemo.h
  roboteam_ai/src/interface/InterfaceValues.cpp
  roboteam_ai/src/interface/InterfaceValues.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/io/IOManager.h
  roboteam_ai/src/utilities/Pause.cpp
  roboteam_ai/src/utilities/Pause.h
  roboteam_ai/test/UtilTests/JoyStickTest.cpp
Labels: Work in progress, feature
