Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-07, with the labels that each got.

#640 fix PID's being way too slow.
  roboteam_ai/src/skills/PenaltyKeeper.cpp
  roboteam_ai/src/skills/Skill.cpp
Labels: Critical priority

#641 a stupid mistake in penalty keeper
  roboteam_ai/src/skills/Skill.cpp
Labels: Critical priority

#651 Robocup/reflect kick
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/conditions/CanReflectKick.cpp
  roboteam_ai/src/conditions/CanReflectKick.h
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/jsons/roles/ReflectKickTest.json
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/strategies/test_reflect_kick_strategy.json
  roboteam_ai/src/jsons/tactics/normal_play_offense_tactic.json
  roboteam_ai/src/jsons/tactics/test_pass_tactic.json
  roboteam_ai/src/jsons/tactics/test_reflect_kick_tactic.json
  roboteam_ai/src/skills/ReflectKick.cpp
  roboteam_ai/src/skills/ReflectKick.h
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/test/ConditionTests/CanReflectKickTest.cpp
Labels: Ready for merge, duplicate

#661 1. fix TCP delay
  roboteam_ai/src/io/IOManager.cpp
Labels: BEFORE MRL

#660 2. Robocup Penalty
  roboteam_ai/src/conditions/CanPlay.cpp
  roboteam_ai/src/jsons/roles/penalty_shooter_prepare_role.json
  roboteam_ai/src/jsons/tactics/prepare_penalty_us_tactic.json
  roboteam_ai/src/skills/ShootPenalty.cpp
  roboteam_ai/src/skills/ShootPenalty.h
  roboteam_ai/src/skills/Wait.cpp
  roboteam_ai/src/skills/Wait.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
Labels: BEFORE MRL

#666 3.Robocup/ball handling edits
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/coach/BallplacementCoach.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/DribbleForwards.cpp
  roboteam_ai/src/jsons/tactics/one_robot_ballplacement_tactic.json
  roboteam_ai/src/skills/Dribble.cpp
Labels: BEFORE MRL

#667 5. Extract receiver going towards ball from op-amp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
Labels: BEFORE MRL
