Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-10, with the labels that each got.

#694 Use macOS as VM for travis (repairs CI)
  .travis.yml
  CMakeLists.txt
Labels: Ready for merge

#689 Refactor/control methods
  CMakeLists.txt
  include/roboteam_ai/control/PosController.h
  include/roboteam_ai/control/ballHandling/BallHandlePosControl.h
  include/roboteam_ai/control/controllers/BaseController.h
  include/roboteam_ai/control/controllers/PidController.h
  include/roboteam_ai/control/controllers/PidTwoAxesController.h
  include/roboteam_ai/control/pid.h
  include/roboteam_ai/control/shotControllers/ShotController.h
  src/control/PosController.cpp
  src/control/ballHandling/BallHandlePosControl.cpp
  src/control/controllers/PidController.cpp
  src/control/controllers/PidTwoAxesController.cpp
  src/control/numTrees/NumTreePosControl.cpp
  src/control/pid.cpp
  src/control/shotControllers/ShotController.cpp
Labels: refactor

#701 Hotfix/fix master
  include/roboteam_ai/ApplicationManager.h
  include/roboteam_ai/skills/Dribble.h
  roboteam_ai/src/conditions/BallNotTooClose.cpp
  roboteam_ai/src/conditions/BallNotTooClose.h
  src/skills/Pass.cpp
Labels: high priority

#700 add slack key
  .travis.yml
Labels: Ready for review

#697 Update to new roboteam_proto protocol
  include/roboteam_ai/Settings/Settings.h
  include/roboteam_ai/control/RobotCommand.h
  include/roboteam_ai/demo/JoystickDemo.h
  include/roboteam_ai/io/IOManager.h
  include/roboteam_ai/skills/Skill.h
  include/roboteam_ai/utilities/GameStateManager.hpp
  include/roboteam_ai/utilities/StrategyManager.h
  include/roboteam_ai/world/Ball.h
  include/roboteam_ai/world/FieldMessage.h
  include/roboteam_ai/world/Robot.h
  include/roboteam_ai/world/World.h
  include/roboteam_ai/world/WorldData.h
  src/Settings/Settings.cpp
  src/demo/JoystickDemo.cpp
  src/io/IOManager.cpp
  src/skills/Skill.cpp
  src/utilities/GameStateManager.cpp
  src/utilities/Pause.cpp
  src/utilities/StrategyManager.cpp
  src/world/Ball.cpp
  src/world/FieldMessage.cpp
  src/world/Robot.cpp
  src/world/World.cpp
  test/ConditionTests/TheyHaveBallTest.cpp
  test/UtilTests/RefereeTest.cpp
  test/UtilTests/StrategyManagerTest.cpp
  test/WorldTests/FieldTest.cpp
  test/helpers/FieldHelper.cpp
  test/helpers/FieldHelper.h
  test/helpers/WorldHelper.cpp
  test/helpers/WorldHelper.h
Labels: Ready for review
