Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-03, with the labels that each got.

#146 Feature/new trees
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/jsons/roles/PenaltyKickerRole.json
  roboteam_ai/src/jsons/strategies/PenaltyAtackStrategy.json
  roboteam_ai/src/jsons/tactics/PenaltyAtackTactic.json
  roboteam_ai/src/treeinterp/BTFactory.cpp
Labels: Ready for merge

#149 Embedded world
  CMakeLists.txt
  roboteam_ai/src/conditions/BallInDefenseAreaAndStill.cpp
  roboteam_ai/src/conditions/BallInDefenseAreaAndStill.h
  roboteam_ai/src/conditions/BallKickedToOurGoal.cpp
  roboteam_ai/src/conditions/BallNearOurGoalLineAndStill.cpp
  roboteam_ai/src/conditions/BallNearOurGoalLineAndStill.h
  roboteam_ai/src/conditions/HasBall.cpp
  roboteam_ai/src/conditions/HasBall.hpp
  roboteam_ai/src/conditions/IsBallCloseToBorder.cpp
  roboteam_ai/src/conditions/IsBallCloseToBorder.h
  roboteam_ai/src/conditions/IsCloseToPoint.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.hpp
  roboteam_ai/src/conditions/IsRobotClosestToBall.cpp
  roboteam_ai/src/control/ControlGoToPos.cpp
  roboteam_ai/src/control/PositionController.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.h
  roboteam_ai/src/demo/JoystickDemo.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/jsons/roles/BallPlacementBot.json
  roboteam_ai/src/jsons/roles/DemoAttacker.json
  roboteam_ai/src/jsons/roles/DemoAttackerRole.json
  roboteam_ai/src/jsons/roles/DemoKeeper.json
  roboteam_ai/src/jsons/roles/DemoKeeper_backup.json
  roboteam_ai/src/jsons/roles/DemoKeeper_backup_rob.json
  roboteam_ai/src/jsons/strategies/DemoStrategy.json
  roboteam_ai/src/jsons/strategies/DemoTeamTwenteStrategy.json
  roboteam_ai/src/jsons/tactics/DemoAttackerTactic.json
  roboteam_ai/src/jsons/tactics/DemoTactic.json
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Attack.h
  roboteam_ai/src/skills/BasicGoToPos.cpp
  roboteam_ai/src/skills/BasicGoToPos.h
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/Dribble.h
  roboteam_ai/src/skills/DribbleRotate.cpp
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GetBall.h
  roboteam_ai/src/skills/GoToPos.cpp
  roboteam_ai/src/skills/GoToPos.h
  roboteam_ai/src/skills/Halt.cpp
  roboteam_ai/src/skills/Halt.h
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/skills/RotateToAngle.cpp
  roboteam_ai/src/skills/RotateToAngle.h
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Coach.cpp
  roboteam_ai/src/utilities/Coach.h
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/Field.cpp
  roboteam_ai/src/utilities/Field.h
  roboteam_ai/test/ConditionTests/IsBallCloseToBorderTest.cpp
Labels: Waiting for other PR

#184 use roboteam_utils master for travis
  .travis.rosinstall
Labels: Ready for merge

#186 Bugfix/copy jsons
  CMakeLists.txt
Labels: Ready for review, enhancement

#199 restructure coach
  CMakeLists.txt
  roboteam_ai/src/coach/Ballplacement.cpp
  roboteam_ai/src/coach/Ballplacement.h
  roboteam_ai/src/coach/GeneralPositionCoach.cpp
  roboteam_ai/src/coach/GeneralPositionCoach.h
  roboteam_ai/src/coach/PassCoach.cpp
  roboteam_ai/src/coach/PassCoach.h
  roboteam_ai/src/conditions/Condition.h
  roboteam_ai/src/conditions/IsBeingPassedTo.cpp
  roboteam_ai/src/conditions/IsBeingPassedTo.h
  roboteam_ai/src/conditions/TheyHaveBall.cpp
  roboteam_ai/src/control/PositionController.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/PositionControlIncludes.h
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/AvoidBall.cpp
  roboteam_ai/src/skills/BasicGoToPos.cpp
  roboteam_ai/src/skills/Defend.cpp
  roboteam_ai/src/skills/Defend.h
  roboteam_ai/src/skills/DefendOnRobot.cpp
  roboteam_ai/src/skills/DefendOnRobot.h
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/DribbleRotate.cpp
  roboteam_ai/src/skills/EnterFormation.cpp
  roboteam_ai/src/skills/EnterFormation.h
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GoAroundPos.cpp
  roboteam_ai/src/skills/GoToPos.cpp
  roboteam_ai/src/skills/Harass.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Skill.h
  roboteam_ai/src/utilities/Coach.cpp
  roboteam_ai/src/utilities/Coach.h
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
  roboteam_ai/test/CoachTests/BallPlacementCoachTest.cpp
  roboteam_ai/test/CoachTests/GeneralPositionCoachTest.cpp
  roboteam_ai/test/ConditionTests/IsBallCloseToBorderTest.cpp
  roboteam_ai/test/SkillTests/DefendTest.cpp
  roboteam_ai/test/SkillTests/FormationTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/UtilTests/CoachTest.cpp
  roboteam_ai/test/UtilTests/WorldTest.cpp
Labels: Ready for review

#201 Feature/basic go to pos
  CMakeLists.txt
  roboteam_ai/src/jsons/keeper/keeperTest1.json
  roboteam_ai/src/jsons/roles/BallPlacementBot.json
  roboteam_ai/src/jsons/roles/DemoAttacker.json
  roboteam_ai/src/jsons/roles/DemoAttackerRole.json
  roboteam_ai/src/jsons/roles/DemoKeeper.json
  roboteam_ai/src/jsons/roles/DemoKeeper_backup.json
  roboteam_ai/src/jsons/roles/DemoKeeper_backup_rob.json
  roboteam_ai/src/jsons/roles/Keeperv2.json
  roboteam_ai/src/jsons/roles/SimpleDefendRole.json
  roboteam_ai/src/jsons/roles/testAvoidanceBot.json
  roboteam_ai/src/jsons/roles/testAvoidanceRole.json
  roboteam_ai/src/jsons/roles/testRole.json
  roboteam_ai/src/jsons/tactics/BallPlacementUsTactic.json
  roboteam_ai/src/jsons/tactics/DemoAttackerTactic.json
  roboteam_ai/src/jsons/tactics/DemoTactic.json
  roboteam_ai/src/jsons/tactics/EnterFormationTactic.json
  roboteam_ai/src/jsons/tactics/OffenseTactic.json
  roboteam_ai/src/jsons/tactics/OneAttackerOneDefenderTactic.json
  roboteam_ai/src/jsons/tactics/OneAttackerTactic.json
  roboteam_ai/src/jsons/tactics/OneDefenderTactic.json
  roboteam_ai/src/jsons/tactics/PassTactic.json
  roboteam_ai/src/jsons/tactics/PenaltyAtackTactic.json
  roboteam_ai/src/jsons/tactics/QualificationTactic.json
  roboteam_ai/src/jsons/tactics/SingleKeeperTactic.json
  roboteam_ai/src/jsons/tactics/TwoDefendersTactic.json
  roboteam_ai/src/skills/BasicGoToPos.cpp
  roboteam_ai/src/skills/BasicGoToPos.h
  roboteam_ai/src/skills/GTPSpecial.cpp
  roboteam_ai/src/skills/GTPSpecial.h
  roboteam_ai/src/skills/GoToPos.cpp
  roboteam_ai/src/skills/GoToPos.h
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/SkillTests/GoToPosTest.cpp
Labels: Work in progress

#198 Constant Refactor
  roboteam_ai/src/conditions/BallKickedToOurGoal.cpp
  roboteam_ai/src/conditions/BallKickedToOurGoal.h
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.h
  roboteam_ai/src/control/positionControllers/PositionControlIncludes.h
  roboteam_ai/src/skills/AvoidBall.cpp
  roboteam_ai/src/skills/AvoidBall.h
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/Dribble.h
  roboteam_ai/src/skills/DribbleRotate.cpp
  roboteam_ai/src/skills/DribbleRotate.h
  roboteam_ai/src/skills/EnterFormation.cpp
  roboteam_ai/src/skills/EnterFormation.h
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GetBall.h
  roboteam_ai/src/skills/GoAroundPos.cpp
  roboteam_ai/src/skills/GoAroundPos.h
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/SkillTests/DefendOnRobotTest.cpp
Labels: Ready for review

#163 Feature/offensive positioning
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/coach/CoachHeuristics.cpp
  roboteam_ai/src/coach/CoachHeuristics.h
  roboteam_ai/src/coach/GeneralPositionCoach.cpp
  roboteam_ai/src/coach/GeneralPositionCoach.h
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/OffensiveCoach.h
  roboteam_ai/src/coach/PassCoach.cpp
  roboteam_ai/src/coach/PassCoach.h
  roboteam_ai/src/conditions/Condition.h
  roboteam_ai/src/conditions/HasClearShot.cpp
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/PositionControlIncludes.h
  roboteam_ai/src/interface/drawer.cpp
  roboteam_ai/src/interface/drawer.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
  roboteam_ai/src/jsons/roles/DemoAttackerRole.json
  roboteam_ai/src/jsons/roles/MidFielder.json
  roboteam_ai/src/jsons/roles/MidFielderRole.json
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/strategies/PassAndShootStrategy.json
  roboteam_ai/src/jsons/strategies/SideAttackerStrategy.json
  roboteam_ai/src/jsons/tactics/PassAndShootTactic.json
  roboteam_ai/src/jsons/tactics/SideAttackerTactic.json
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/SideAttacker.h
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/test/ApplicationManagerTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/UtilTests/OffensiveCoachTest.cpp
Labels: Ready for review

#205 game analyzer
  CMakeLists.txt
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/analysis/AnalysisReport.cpp
  roboteam_ai/src/analysis/AnalysisReport.h
  roboteam_ai/src/analysis/GameAnalyzer.cpp
  roboteam_ai/src/analysis/GameAnalyzer.h
  roboteam_ai/src/analysis/RobotDanger.cpp
  roboteam_ai/src/analysis/RobotDanger.h
  roboteam_ai/src/conditions/TheyHaveBall.cpp
  roboteam_ai/src/conditions/WeHaveBall.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/dangerfinder/DangerData.cpp
  roboteam_ai/src/dangerfinder/DangerData.h
  roboteam_ai/src/dangerfinder/DangerFinder.cpp
  roboteam_ai/src/dangerfinder/DangerFinder.h
  roboteam_ai/src/dangerfinder/PartialResult.cpp
  roboteam_ai/src/dangerfinder/PartialResult.h
  roboteam_ai/src/dangerfinder/modules/CanShootModule.cpp
  roboteam_ai/src/dangerfinder/modules/CanShootModule.h
  roboteam_ai/src/dangerfinder/modules/DangerModule.cpp
  roboteam_ai/src/dangerfinder/modules/DangerModule.h
  roboteam_ai/src/dangerfinder/modules/DistanceModule.cpp
  roboteam_ai/src/dangerfinder/modules/DistanceModule.h
  roboteam_ai/src/dangerfinder/modules/FreeModule.cpp
  roboteam_ai/src/dangerfinder/modules/FreeModule.h
  roboteam_ai/src/dangerfinder/modules/HasBallModule.cpp
  roboteam_ai/src/dangerfinder/modules/HasBallModule.h
  roboteam_ai/src/dangerfinder/modules/OrientationModule.cpp
  roboteam_ai/src/dangerfinder/modules/OrientationModule.h
  roboteam_ai/src/interface/RobotsWidget.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
  roboteam_ai/src/skills/DefendOnRobot.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/Field.cpp
  roboteam_ai/src/utilities/Field.h
  roboteam_ai/src/utilities/Referee.cpp
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
  roboteam_ai/test/ApplicationManagerTest.cpp
  roboteam_ai/test/UtilTests/DangerFinderTest.cpp
  roboteam_ai/test/UtilTests/FieldTest.cpp
Labels: enhancement, feature, high priority

#220 fix qt warning
  roboteam_ai/src/interface/RobotsWidget.cpp
  roboteam_ai/src/interface/mainWindow.cpp
Labels: Ready for merge, Ready for review

#215 Hotfix/bt factory
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/Switches.h
  roboteam_ai/src/interface/TreeVisualizerWidget.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/jsons/tactics/QualificationTactic.json
  roboteam_ai/src/roboteam_ai.cpp
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/treeinterp/BTFactory.h
  roboteam_ai/src/treeinterp/JsonReader.cpp
  roboteam_ai/src/treeinterp/JsonReader.h
  roboteam_ai/src/treeinterp/PropertiesParser.cpp
  roboteam_ai/src/treeinterp/PropertiesParser.h
  roboteam_ai/src/treeinterp/TreeInterpreter.cpp
  roboteam_ai/src/treeinterp/TreeInterpreter.h
  roboteam_ai/test/ApplicationManagerTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
  roboteam_ai/test/TacticTests/DefaultTacticTest.cpp
  roboteam_ai/test/TreeInterpreterTests/BTFactoryTest.cpp
  roboteam_ai/test/UtilTests/JsonTest.cpp
  roboteam_ai/test/UtilTests/PropertiesParserTest.cpp
Labels: Ready for merge

#212 refactor publish robotcommand
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/AvoidBall.cpp
  roboteam_ai/src/skills/BasicGoToPos.cpp
  roboteam_ai/src/skills/Chip.cpp
  roboteam_ai/src/skills/Defend.cpp
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/DribbleRotate.cpp
  roboteam_ai/src/skills/EnterFormation.cpp
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GoAroundPos.cpp
  roboteam_ai/src/skills/GoBehindBall.cpp
  roboteam_ai/src/skills/GoToPos.cpp
  roboteam_ai/src/skills/Halt.cpp
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Kick.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/RotateToAngle.cpp
  roboteam_ai/src/skills/RotateToAngle.h
  roboteam_ai/src/skills/ShootFreeKick.cpp
  roboteam_ai/src/skills/ShootPenalty.cpp
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/skills/Skill.h
  roboteam_ai/src/skills/SkillGoToPos.cpp
  roboteam_ai/src/skills/TurnGeneva.cpp
Labels: Ready for merge
