Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-01, with the labels that each got.

#59 Feature/remove pid
  CMakeLists.txt
  roboteam_ai/src/control/ControlGoToPos.cpp
  roboteam_ai/src/control/ControlGoToPos.h
  roboteam_ai/src/control/Controller.cpp
  roboteam_ai/src/control/Controller.h
  roboteam_ai/src/control/PID.cpp
  roboteam_ai/src/control/PID.h
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.h
  roboteam_ai/src/control/controlGoToPos/goToPosInclude.h
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/skills/Skill.h
  roboteam_ai/src/utilities/Coach.cpp
Labels: Ready for merge

#64 Cleanup Cmake
  CMakeLists.txt
  cmake_modules/FindSDL2.cmake
  cmake_modules/FindSDL2TTF.cmake
  package.xml
Labels: Ready for merge

#58 Feature/keeper visualization
  roboteam_ai/src/interface/drawer.cpp
  roboteam_ai/src/interface/drawer.h
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
  roboteam_ai/src/roboteam_ai.cpp
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/utilities/Constants.h
Labels: Ready for review

#63 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Ready for review, enhancement

#62 make the ball a pointer
  CMakeLists.txt
  roboteam_ai/src/bt/Leaf.cpp
  roboteam_ai/src/bt/Leaf.hpp
  roboteam_ai/src/conditions/BallKickedToOurGoal.cpp
  roboteam_ai/src/conditions/HasBall.cpp
  roboteam_ai/src/conditions/WeHaveBall.cpp
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Attack.h
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/Dribble.h
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GetBall.h
  roboteam_ai/src/skills/GoToPos.cpp
  roboteam_ai/src/skills/GoToPosLuTh.cpp
  roboteam_ai/src/skills/Harass.cpp
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Rotate.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/utilities/Coach.cpp
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
Labels: Ready for review

#67 Feature/fixtests
  CMakeLists.txt
  roboteam_ai/src/bt/composites/MemSelector.hpp
  roboteam_ai/src/conditions/IsInDefenseArea.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.hpp
  roboteam_ai/src/conditions/IsInZone.cpp
  roboteam_ai/src/conditions/IsRobotClosestToBall.cpp
  roboteam_ai/src/dangerfinder/DangerData.cpp
  roboteam_ai/src/interface/drawer.cpp
  roboteam_ai/src/jsons/jsonBasicTest.json
  roboteam_ai/src/jsons/jsonBasicTestTwo.json
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/test/BTFactoryTest.cpp
  roboteam_ai/test/BtTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/ConditionTests/IsOnOurSideTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
  roboteam_ai/test/ControUtilsTest.cpp
  roboteam_ai/test/ControlUtilsTest.cpp
  roboteam_ai/test/DangerFinderTest.cpp
  roboteam_ai/test/IOTest.cpp
  roboteam_ai/test/JsonTest.cpp
  roboteam_ai/test/SkillTests/KickTest.cpp
  roboteam_ai/test/SkillTests/RotateTest.cpp
  roboteam_ai/test/WorldTest.cpp
Labels: Ready for review

#73 Feature/fix robot dealer test
  CMakeLists.txt
  roboteam_ai/src/conditions/IsInDefenseArea.cpp
  roboteam_ai/src/jsons/tactics/BallPlacementUsTactic.json
  roboteam_ai/src/skills/Rotate.cpp
  roboteam_ai/src/skills/Rotate.h
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/test/ConditionTests/HasBallTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
  roboteam_ai/test/RefStateManagerTest.cpp
  roboteam_ai/test/RobotDealerTest.cpp
  roboteam_ai/test/SkillTests/GoToPosTest.cpp
  roboteam_ai/test/SkillTests/KickTest.cpp
  roboteam_ai/test/SkillTests/RotateTest.cpp
  roboteam_ai/test/WorldTest.cpp
Labels: Ready for review, high priority

#55 Feature/travis
  .travis.rosinstall
  .travis.yml
  CMakeLists.txt
  README.md
  package.xml
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.cpp
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/skills/GoToPosLuTh.cpp
  roboteam_ai/src/treeinterp/JsonReader.cpp
Labels: Ready for review, feature

#69 feature/ContolGTP
  roboteam_ai/src/control/ControlGoToPos.cpp
  roboteam_ai/src/control/ControlGoToPos.h
  roboteam_ai/src/control/Controller.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosBallControl.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosBallControl.h
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.cpp
  roboteam_ai/src/control/controlGoToPos/ControlGoToPosLuTh.h
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/utilities/Coach.cpp
Labels: Ready for review

#79 Feature/getrobotsforids
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
  roboteam_ai/test/WorldTest.cpp
Labels: Ready for review

#83 Make travis build twice as fast
  .travis.yml
Labels: Ready for review

#82 Add mutexes to Field & World
  roboteam_ai/src/utilities/Field.cpp
  roboteam_ai/src/utilities/Field.h
  roboteam_ai/src/utilities/World.cpp
  roboteam_ai/src/utilities/World.h
Labels: Ready for merge

#84 fix io test
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/test/IOTest.cpp
Labels: Ready for review

#77 Auto coverage reports
  .travis.yml
  cmake_modules/CodeCoverage.cmake
Labels: Ready for review

#53 Update package.xml
  package.xml
Labels: Ready for review, enhancement

#85 Feature/more tests
  CMakeLists.txt
  cmake_modules/CodeCoverage.cmake
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/src/bt/bt.hpp
  roboteam_ai/src/bt/tactics/DemoTactic.cpp
  roboteam_ai/src/bt/tactics/DemoTactic.h
  roboteam_ai/src/bt/tactics/ParallelSequenceTest.cpp
  roboteam_ai/src/bt/tactics/ParallelSequenceTest.h
  roboteam_ai/src/bt/tactics/RandomTactic.cpp
  roboteam_ai/src/bt/tactics/RandomTactic.h
  roboteam_ai/src/control/Controller.cpp
  roboteam_ai/src/control/Controller.h
  roboteam_ai/src/io/IOManager.cpp
  roboteam_ai/src/io/IOManager.h
  roboteam_ai/src/roboteam_ai.cpp
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/TreeInterpreter.h
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/test/ApplicationManagerTest.cpp
  roboteam_ai/test/ControllerTest.cpp
  roboteam_ai/test/RobotDealerTest.cpp
  roboteam_ai/test/TacticTests/DefaultTacticTest.cpp
  roboteam_ai/test/WorldTest.cpp
Labels: Ready for review

#91 fix ros rate performance bug
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/ApplicationManager.h
  roboteam_ai/test/ApplicationManagerTest.cpp
Labels: Critical priority, Ready for review

#94 add interface for luth pid
  CMakeLists.txt
  roboteam_ai/src/interface/InterfaceValues.cpp
  roboteam_ai/src/interface/InterfaceValues.h
  roboteam_ai/src/interface/mainWindow.cpp
  roboteam_ai/src/interface/mainWindow.h
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/InterfaceTest.cpp
Labels: Ready for merge, feature

#100 add launch file to start two teams at once
  CMakeLists.txt
  launch/two-teams.launch
  package.xml
  roboteam_ai/src/roboteam_ai.cpp
Labels: Ready for review

#114 Fix keeper
  roboteam_ai/src/jsons/roles/Keeper.json
  roboteam_ai/src/jsons/strategies/DemoTeamTwenteStrategy.json
  roboteam_ai/src/jsons/strategies/EnterFormationStrategy.json
  roboteam_ai/src/jsons/strategies/KeeperStrategy.json
  roboteam_ai/src/jsons/strategies/OneVersusThreeStrategy.json
  roboteam_ai/src/jsons/tactics/KeeperTactic.json
  roboteam_ai/src/jsons/tactics/KeeperTestTactic.json
  roboteam_ai/src/jsons/tactics/SingleKeeperTactic.json
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/treeinterp/config_files/skills.csv
Labels: Critical priority, Ready for merge, Ready for review, bug

#122 fix robot colors in interface to match sides
  roboteam_ai/src/interface/widget.cpp
  roboteam_ai/src/interface/widget.h
  roboteam_ai/src/utilities/Constants.h
Labels: Ready for review

#116 Add error handling
  roboteam_ai/src/treeinterp/BTFactory.cpp
  roboteam_ai/src/treeinterp/JsonReader.cpp
  roboteam_ai/src/treeinterp/Switches.cpp
  roboteam_ai/src/treeinterp/Switches.h
  roboteam_ai/src/treeinterp/TreeInterpreter.cpp
  roboteam_ai/src/treeinterp/TreeInterpreter.h
Labels: Ready for merge, Work in progress
