Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-05, with the labels that each got.

#430 QOL improvements and some bugfixes for keeper. Put it further forwards
  roboteam_ai/src/conditions/BallInDefenseAreaAndStill.cpp
  roboteam_ai/src/jsons/keeper/keeper_default_tactic.json
  roboteam_ai/src/jsons/roles/Keeper.json
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Field.cpp
Labels: Ready for review

#449 Hotfix/keeper claiming and fix defence area implementation
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/bt/tactics/DefaultTactic.cpp
  roboteam_ai/src/coach/midField/HarassRobotCoach.cpp
  roboteam_ai/src/control/PositionUtils.cpp
  roboteam_ai/src/interface/api/Input.cpp
  roboteam_ai/src/interface/api/Input.h
  roboteam_ai/src/skills/formations/Formation.cpp
  roboteam_ai/src/skills/formations/KickOffUsFormation.cpp
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/RobotDealer.h
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/test/AnalysisTests/DecisionmakerTest.cpp
  roboteam_ai/test/ConditionTests/BallInDefenseAreaAndStillTest.cpp
  roboteam_ai/test/ConditionTests/IsInDefenseAreaTest.cpp
  roboteam_ai/test/TacticTests/DefaultTacticTest.cpp
  roboteam_ai/test/WorldTests/FieldTest.cpp
Labels: Critical priority, Ready for review, high priority

#443 Update robot objects in worldstate instead of replacing them
  roboteam_ai/src/analysis/GameAnalyzer.cpp
  roboteam_ai/src/interface/widgets/widget.cpp
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/src/world/BallPossession.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
  roboteam_ai/src/world/WorldData.h
  roboteam_ai/test/helpers/WorldHelper.cpp
Labels: Ready for review, high priority, refactor

#445 fix refstate is normal play condition when not using ref
  roboteam_ai/src/conditions/RefStateIsNormalPlay.cpp
Labels: Low priority, enhancement

#448 Feature/robot specific control
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/conditions/TheyHaveBall.h
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/skills/ActiveStop.cpp
  roboteam_ai/src/skills/ActiveStop.h
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Attack.h
  roboteam_ai/src/skills/BallPlacement/BallPlacementPass.cpp
  roboteam_ai/src/skills/BallPlacement/BallPlacementReceive.cpp
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/skills/CoachDefend.h
  roboteam_ai/src/skills/Defend.cpp
  roboteam_ai/src/skills/Defend.h
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/DemoAttack.h
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/MidFieldHarasser.h
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/skills/ReflectKick.cpp
  roboteam_ai/src/skills/ReflectKick.h
  roboteam_ai/src/skills/ShootFreeKick.cpp
  roboteam_ai/src/skills/ShootFreeKick.h
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/SideAttacker.h
  roboteam_ai/src/skills/formations/DefendFreeKick.cpp
  roboteam_ai/src/skills/formations/Formation.cpp
  roboteam_ai/src/skills/formations/Formation.h
  roboteam_ai/src/skills/formations/PenaltyFormation.cpp
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/test/SkillTests/DefendTest.cpp
  roboteam_ai/test/WorldTests/FieldTest.cpp
Labels: enhancement, feature, high priority

#464 Feature/fix receive defense area
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/world/Field.cpp
Labels: Ready for merge

#475 Change PID library and constants
  roboteam_ai/src/control/pid.cpp
  roboteam_ai/src/jsons/tactics/calibration_tactic.json
  roboteam_ai/src/utilities/Constants.cpp
Labels: Quick fix

#471 Feature/tests
  .travis.yml
  CMakeLists.txt
  README.md
  cmake_modules/CodeCoverage.cmake
  repository.rosinstall
  roboteam_ai/src/bt/RoleDivider.cpp
  roboteam_ai/src/bt/RoleDivider.h
  roboteam_ai/src/bt/Tactic.cpp
  roboteam_ai/src/bt/Tactic.h
  roboteam_ai/src/bt/tactics/DefaultTactic.cpp
  roboteam_ai/src/bt/tactics/DefaultTactic.h
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/interface/api/Output.cpp
  roboteam_ai/src/utilities/GameState.h
  roboteam_ai/src/utilities/StrategyManager.h
  roboteam_ai/src/world/Ball.cpp
  roboteam_ai/src/world/Ball.h
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/src/world/BallPossession.h
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/src/world/Field.h
  roboteam_ai/src/world/History.cpp
  roboteam_ai/src/world/History.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/WorldData.h
  roboteam_ai/src/world/WorldManager.cpp
  roboteam_ai/src/world/WorldManager.h
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
  roboteam_ai/test/ControlTests/HungarianTest.cpp
  roboteam_ai/test/ControlTests/PosControllerTests/NumTreePosControlTest.cpp
  roboteam_ai/test/ControlTests/PosControllerTests/RobotCommandTest.cpp
  roboteam_ai/test/ControlTests/ShotControllerTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
  roboteam_ai/test/UtilTests/IOTest.cpp
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
  roboteam_ai/test/WorldTests/BallPossessionTests.cpp
  roboteam_ai/test/WorldTests/FieldTest.cpp
  roboteam_ai/test/WorldTests/HistoryTests.cpp
  roboteam_ai/test/btTests/RoleDividerTests.cpp
  roboteam_ai/test/roboteam_utils_Tests/AngleTest.cpp
Labels: Ready for merge

#442 Feature/better attacker
  roboteam_ai/src/ApplicationManager.cpp
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/coach/OffensiveCoach.h
  roboteam_ai/src/coach/heuristics/CoachHeuristics.cpp
  roboteam_ai/src/coach/heuristics/CoachHeuristics.h
  roboteam_ai/src/coach/heuristics/OffensiveScore.cpp
  roboteam_ai/src/coach/heuristics/OffensiveScore.h
  roboteam_ai/src/conditions/HasClearShot.cpp
  roboteam_ai/src/conditions/HasClearShot.h
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/ForcePosControl.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/control/shotControllers/ShotData.h
  roboteam_ai/src/interface/api/Output.cpp
  roboteam_ai/src/interface/api/Output.h
  roboteam_ai/src/interface/api/Toggles.cpp
  roboteam_ai/src/interface/api/Toggles.h
  roboteam_ai/src/interface/widgets/widget.cpp
  roboteam_ai/src/interface/widgets/widget.h
  roboteam_ai/src/jsons/roles/new_robot_attacker.json
  roboteam_ai/src/jsons/strategies/new_robot_strategy.json
  roboteam_ai/src/jsons/tactics/new_robot_tactic.json
  roboteam_ai/src/roboteam_ai.cpp
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/AvoidBall.cpp
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/skills/Skill.h
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/src/world/Field.h
  roboteam_ai/src/world/WorldData.h
  roboteam_ai/test/CoachTests/OffensiveCoachTest.cpp
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
Labels: Epic, Ready for review

#477 Refactor gotoposes
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/bt/Leaf.cpp
  roboteam_ai/src/bt/Node.cpp
  roboteam_ai/src/bt/Node.hpp
  roboteam_ai/src/coach/OffensiveCoach.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/positionControllers/BallHandlePosControl.cpp
  roboteam_ai/src/control/positionControllers/BallHandlePosControl.h
  roboteam_ai/src/control/positionControllers/ForcePosControl.cpp
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/interface/api/Toggles.cpp
  roboteam_ai/src/interface/widgets/RobotsWidget.cpp
  roboteam_ai/src/interface/widgets/TreeVisualizerWidget.cpp
  roboteam_ai/src/skills/BallPlacementWithInterface.cpp
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/DriveWithInterface.cpp
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/skills/Skill.h
  roboteam_ai/src/skills/gotopos/GoAroundPos.cpp
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/BallPossession.cpp
  roboteam_ai/src/world/History.cpp
  roboteam_ai/src/world/History.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/WorldData.h
  roboteam_ai/test/ControlTests/ControlUtilsTest.cpp
  roboteam_ai/test/InterfaceTests/TreeVisualizerTest.cpp
  roboteam_ai/test/TreeInterpreterTests/BtTest.cpp
  roboteam_ai/test/WorldTests/BallPossessionTests.cpp
Labels: Ready for merge, Ready for review

#494 Feature/refactor ball handle
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/DribbleBackwards.cpp
  roboteam_ai/src/control/ballHandling/DribbleBackwards.h
  roboteam_ai/src/control/ballHandling/DribbleForwards.cpp
  roboteam_ai/src/control/ballHandling/DribbleForwards.h
  roboteam_ai/src/control/ballHandling/RotateAroundBall.cpp
  roboteam_ai/src/control/ballHandling/RotateAroundBall.h
  roboteam_ai/src/control/ballHandling/RotateWithBall.cpp
  roboteam_ai/src/control/ballHandling/RotateWithBall.h
  roboteam_ai/src/control/positionControllers/BallHandlePosControl.cpp
  roboteam_ai/src/control/positionControllers/BallHandlePosControl.h
  roboteam_ai/src/control/positionControllers/BasicPosControl.h
  roboteam_ai/src/control/positionControllers/ForcePosControl.cpp
  roboteam_ai/src/control/positionControllers/ForcePosControl.h
  roboteam_ai/src/control/positionControllers/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/NumTreePosControl.h
  roboteam_ai/src/control/positionControllers/PosController.h
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/skills/ActiveStop.cpp
  roboteam_ai/src/skills/BallPlacementWithInterface.h
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/Dribble.h
  roboteam_ai/src/skills/DribbleForward.h
  roboteam_ai/src/skills/DribbleRotate.h
  roboteam_ai/src/skills/GetBall.h
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptRobot.cpp
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/skills/ReflectKick.cpp
  roboteam_ai/src/skills/SideAttacker.cpp
  roboteam_ai/src/skills/Skill.cpp
  roboteam_ai/src/skills/ballPlacement/BallPlacementPass.cpp
  roboteam_ai/src/skills/ballPlacement/BallPlacementPass.h
  roboteam_ai/src/skills/ballPlacement/BallPlacementReceive.cpp
  roboteam_ai/src/skills/ballPlacement/BallPlacementReceive.h
  roboteam_ai/src/skills/formations/DefendFreeKick.cpp
  roboteam_ai/src/skills/formations/Formation.cpp
  roboteam_ai/src/skills/formations/PenaltyFormation.cpp
  roboteam_ai/src/skills/gotopos/GTPWithBall.h
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
  roboteam_ai/src/skills/gotopos/GoToPos.h
  roboteam_ai/src/skills/gotopos/SkillGoToPos.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/world/Ball.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/World.cpp
Labels: Ready for merge, Ready for review

#467 New Comm
  roboteam_ai/src/skills/Dribble.cpp
  roboteam_ai/src/skills/DribbleRotate.cpp
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/SlingShot.cpp
Labels: Ready for review

#473 Feature/fix defenders oscillations
  roboteam_ai/src/coach/defence/DefenceDealer.cpp
  roboteam_ai/src/coach/defence/DefenceDealer.h
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.h
  roboteam_ai/src/control/PositionUtils.cpp
  roboteam_ai/src/skills/CoachDefend.cpp
Labels: Ready for review

#482 Feature/defender tests and bug fixes
  CMakeLists.txt
  roboteam_ai/src/coach/defence/DefenceDealer.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.cpp
  roboteam_ai/src/coach/defence/DefencePositionCoach.h
  roboteam_ai/src/skills/CoachDefend.cpp
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/test/CoachTests/DefensiveCoachTest.cpp
  roboteam_ai/test/WorldTests/FieldTest.cpp
  roboteam_ai/test/helpers/FieldHelper.cpp
Labels: Ready for review

#481 Improve midFielder coach
  CMakeLists.txt
  roboteam_ai/src/analysis/DecisionMaker.cpp
  roboteam_ai/src/coach/midField/HarassRobotCoach.cpp
  roboteam_ai/src/coach/midField/HarassRobotCoach.h
  roboteam_ai/src/coach/midField/MidFieldCoach.cpp
  roboteam_ai/src/coach/midField/MidFieldCoach.h
  roboteam_ai/src/skills/MidFieldHarasser.cpp
  roboteam_ai/src/skills/MidFieldHarasser.h
  roboteam_ai/src/skills/gotopos/GoToPos.cpp
Labels: Ready for review
