Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2019-06, with the labels that each got.

#542 fix more than one robot going to the ball
  roboteam_ai/src/coach/GetBallCoach.cpp
  roboteam_ai/src/conditions/ShouldHandleBall.cpp
Labels: Ready for merge, Ready for review

#522 Feature/fix get ball
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/DribbleBackwards.cpp
  roboteam_ai/src/control/ballHandling/DribbleForwards.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.h
  roboteam_ai/src/control/positionControllers/PosController.h
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/skills/BallPlacementWithInterface.cpp
  roboteam_ai/src/skills/BallPlacementWithInterface.h
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/test/ControlTests/ShotControllerTest.cpp
Labels: Ready for merge, Ready for review

#543 Fix halt so it does not send commands after some time
  roboteam_ai/src/jsons/roles/halt_role.json
  roboteam_ai/src/jsons/tactics/halt_tactic.json
  roboteam_ai/src/skills/Halt.cpp
Labels: Ready for merge

#478 Write some tests
  CMakeLists.txt
  roboteam_ai/test/ConditionTests/IsBeingPassedToTest.cpp
  roboteam_ai/test/SkillTests/PassTest.cpp
  roboteam_ai/test/WorldTests/BallPossessionTests.cpp
Labels: Low priority

#556 better interface goalline visual
  roboteam_ai/src/interface/widgets/widget.cpp
Labels: Ready for review, visualization

#559 Show some more useful info when robots have non-working features
  roboteam_ai/src/interface/widgets/VisualizationSettingsWidget.cpp
  roboteam_ai/src/interface/widgets/widget.cpp
  roboteam_ai/src/interface/widgets/widget.h
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/test/InterfaceTests/MainWindowTest.cpp
Labels: Ready for merge

#541 Fix/keeper commands
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/conditions/BallKickedToOurGoal.h
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/positionControllers/PosController.cpp
  roboteam_ai/src/control/positionControllers/PosController.h
  roboteam_ai/src/interface/api/Output.cpp
  roboteam_ai/src/interface/api/Output.h
  roboteam_ai/src/interface/widgets/PidsWidget.cpp
  roboteam_ai/src/jsons/keeper/keeper_default_tactic.json
  roboteam_ai/src/jsons/roles/Keeper.json
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/Keeper.cpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/skills/ReflectKick.cpp
  roboteam_ai/src/skills/ReflectKick.h
  roboteam_ai/src/skills/ballPlacement/BallPlacementReceive.cpp
  roboteam_ai/src/skills/gotopos/GTPSpecial.cpp
  roboteam_ai/src/skills/gotopos/GTPSpecial.h
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/GameStateManager.cpp
  roboteam_ai/src/utilities/GameStateManager.hpp
  roboteam_ai/test/CoachTests/DefensiveCoachTest.cpp
  roboteam_ai/test/ConditionTests/BallKickedToOurGoalTest.cpp
  roboteam_ai/test/ControlTests/PosControllerTests/NumTreePosControlTest.cpp
  roboteam_ai/test/InterfaceTests/InterfaceTest.cpp
Labels: Ready for review

#558 Feature/ball handle get ball
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/DribbleBackwards.cpp
  roboteam_ai/src/control/ballHandling/DribbleBackwards.h
  roboteam_ai/src/control/ballHandling/DribbleForwards.cpp
  roboteam_ai/src/control/ballHandling/DribbleForwards.h
  roboteam_ai/src/control/ballHandling/RotateAroundBall.cpp
  roboteam_ai/src/control/ballHandling/RotateAroundBall.h
  roboteam_ai/src/control/ballHandling/RotateWithBall.cpp
  roboteam_ai/src/control/ballHandling/RotateWithBall.h
  roboteam_ai/src/control/numTrees/Collision.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.h
  roboteam_ai/src/control/positionControllers/BasicPosControl.cpp
  roboteam_ai/src/interface/api/Toggles.cpp
  roboteam_ai/src/interface/api/Toggles.h
  roboteam_ai/src/skills/GetBall.cpp
  roboteam_ai/src/skills/GetBall.h
  roboteam_ai/src/utilities/GameStateManager.cpp
  roboteam_ai/src/world/Ball.cpp
  roboteam_ai/src/world/Ball.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
  roboteam_ai/src/world/WorldData.h
  roboteam_ai/test/ConditionTests/BallKickedToOurGoalTest.cpp
Labels: Ready for review

#562 RobotDealer nullptr checks.
  roboteam_ai/src/utilities/RobotDealer.cpp
Labels: Quick fix, Ready for merge, Ready for review

#566 Feature/optional ballsensor
  roboteam_ai/src/interface/widgets/widget.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/src/world/Robot.h
Labels: feature

#561 Min distance to defense area in ruleset
  CMakeLists.txt
  roboteam_ai/src/interface/widgets/RuleSetWidget.cpp
  roboteam_ai/src/interface/widgets/RuleSetWidget.h
  roboteam_ai/src/interface/widgets/mainWindow.cpp
  roboteam_ai/src/interface/widgets/mainWindow.h
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/GameState.h
  roboteam_ai/src/utilities/GameStateManager.cpp
  roboteam_ai/src/utilities/RuleSet.h
Labels: Ready for review

#551 Make defenders chip quicker in trees
  roboteam_ai/src/jsons/roles/coachDefender.json
  roboteam_ai/src/jsons/tactics/kickoff_them_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_defense_tactic.json
Labels: on hold for now

#549 shotcontroller upgrade for ball sensor
  CMakeLists.txt
  roboteam_ai/src/control/BasicPosControl.cpp
  roboteam_ai/src/control/BasicPosControl.h
  roboteam_ai/src/control/PosController.cpp
  roboteam_ai/src/control/PosController.h
  roboteam_ai/src/control/RobotCommand.h
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/DribbleBackwards.h
  roboteam_ai/src/control/ballHandling/DribbleForwards.h
  roboteam_ai/src/control/ballHandling/RotateAroundBall.h
  roboteam_ai/src/control/ballHandling/RotateWithBall.h
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.h
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/skills/Attack.cpp
  roboteam_ai/src/skills/Attack.h
  roboteam_ai/src/skills/CoachDefend.h
  roboteam_ai/src/skills/DemoAttack.cpp
  roboteam_ai/src/skills/DribbleForward.h
  roboteam_ai/src/skills/Harass.h
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/skills/InterceptRobot.hpp
  roboteam_ai/src/skills/Keeper.h
  roboteam_ai/src/skills/Pass.cpp
  roboteam_ai/src/skills/Pass.h
  roboteam_ai/src/skills/PenaltyKeeper.h
  roboteam_ai/src/skills/Receive.h
  roboteam_ai/src/skills/ReflectKick.h
  roboteam_ai/src/skills/ShootFreeKick.h
  roboteam_ai/src/skills/ShootPenalty.h
  roboteam_ai/src/skills/SlingShot.h
  roboteam_ai/src/skills/gotopos/GoToPos.h
  roboteam_ai/src/skills/gotopos/SkillGoToPos.cpp
  roboteam_ai/src/world/Robot.cpp
  roboteam_ai/test/ControlTests/PosControllerTests/RobotCommandTest.cpp
Labels: Ready for merge, high priority

#575 Make sure all tactics have 8 roles
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/tactics/calibration_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_defense_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_midfield_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_offense_tactic.json
  roboteam_ai/src/jsons/tactics/test_pass_tactic.json
Labels: Ready for review

#574 make numtrees avoid goal
  roboteam_ai/src/control/numTrees/Collision.cpp
  roboteam_ai/src/control/numTrees/Collision.h
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.h
  roboteam_ai/src/jsons/keeper/keeper_default_tactic.json
  roboteam_ai/src/jsons/keeper/keeper_formation_tactic.json
  roboteam_ai/src/skills/gotopos/GTPSpecial.cpp
  roboteam_ai/src/skills/gotopos/GTPSpecial.h
  roboteam_ai/src/world/Field.cpp
  roboteam_ai/src/world/Field.h
Labels: Ready for review

#582 Predict ball being out of field and inside defense area
  roboteam_ai/src/conditions/BallOutOfField.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.cpp
  roboteam_ai/src/conditions/IsInDefenseArea.hpp
  roboteam_ai/src/jsons/roles/Keeper.json
  roboteam_ai/src/jsons/roles/MidFieldHarassRole.json
  roboteam_ai/src/jsons/roles/SideAttacker.json
  roboteam_ai/src/jsons/roles/coachDefender.json
  roboteam_ai/src/jsons/tactics/kickoff_shoot_tactic.json
  roboteam_ai/src/jsons/tactics/kickoff_them_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_defense_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_midfield_tactic.json
  roboteam_ai/src/jsons/tactics/normal_play_offense_tactic.json
  roboteam_ai/src/jsons/tactics/test_pass_tactic.json
  roboteam_ai/src/treeinterp/config_files/conditions.csv
Labels: Ready for merge

#583 Fix bugs in PosControllers
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/coach/GetBallCoach.cpp
  roboteam_ai/src/coach/GetBallCoach.h
  roboteam_ai/src/conditions/IsRobotClosestToBall.cpp
  roboteam_ai/src/conditions/ShouldHandleBall.cpp
  roboteam_ai/src/control/ControlUtils.cpp
  roboteam_ai/src/control/ControlUtils.h
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.cpp
  roboteam_ai/src/control/ballHandling/BallHandlePosControl.h
  roboteam_ai/src/control/ballHandling/RotateAroundBall.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.cpp
  roboteam_ai/src/control/numTrees/NumTreePosControl.h
  roboteam_ai/src/control/pid.cpp
  roboteam_ai/src/control/pid.h
  roboteam_ai/src/control/shotControllers/ShotController.cpp
  roboteam_ai/src/control/shotControllers/ShotController.h
  roboteam_ai/src/interface/api/Input.h
  roboteam_ai/src/interface/api/Output.cpp
  roboteam_ai/src/interface/api/Output.h
  roboteam_ai/src/interface/widgets/PidsWidget.cpp
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/Receive.cpp
  roboteam_ai/src/utilities/Constants.cpp
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/RobotDealer.cpp
  roboteam_ai/src/utilities/RobotDealer.h
  roboteam_ai/src/world/Ball.cpp
  roboteam_ai/src/world/Ball.h
  roboteam_ai/src/world/World.cpp
  roboteam_ai/src/world/World.h
  roboteam_ai/test/ConditionTests/BallInDefenseAreaAndStillTest.cpp
  roboteam_ai/test/ConditionTests/BallKickedToOurGoalTest.cpp
  roboteam_ai/test/ConditionTests/IsRobotClosestToBallTest.cpp
  roboteam_ai/test/helpers/WorldHelper.h
Labels: Ready for merge, high priority

#602 Penalty Rule Compliance
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/keeper/keeper_penalty_defend_tactic.json
  roboteam_ai/src/jsons/keeper/keeper_penalty_prepare_tactic.json
  roboteam_ai/src/jsons/keeper/keeper_penalty_tactic.json
  roboteam_ai/src/jsons/roles/penaltyKeeperPrepareRole.json
  roboteam_ai/src/jsons/strategies/penalty_them_defend_strategy.json
  roboteam_ai/src/jsons/strategies/penalty_them_prepare_strategy.json
  roboteam_ai/src/jsons/strategies/penalty_them_strategy.json
  roboteam_ai/src/skills/PenaltyKeeper.cpp
  roboteam_ai/src/skills/PenaltyKeeper.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
  roboteam_ai/src/utilities/StrategyManager.h
Labels: Ready for review

#607 Fix/keeper checks
  roboteam_ai/src/skills/InterceptBall.cpp
  roboteam_ai/src/skills/InterceptBall.h
  roboteam_ai/src/utilities/Constants.cpp
Labels: Ready for merge

#609 GameStates for ShootOut
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/conditions/ResumePlayAfterPenalty.cpp
  roboteam_ai/src/conditions/ResumePlayAfterPenalty.h
  roboteam_ai/src/jsons/keeper/shootout_prepare_tactic.json
  roboteam_ai/src/jsons/keeper/shootout_shoot_tactic.json
  roboteam_ai/src/jsons/roles/shootout_prepare_role.json
  roboteam_ai/src/jsons/roles/shootout_shoot_role.json
  roboteam_ai/src/jsons/strategies/penalty_them_defend_strategy.json
  roboteam_ai/src/skills/PenaltyKeeper.cpp
  roboteam_ai/src/skills/gotopos/GoBehindBall.cpp
  roboteam_ai/src/skills/gotopos/GoBehindBall.h
  roboteam_ai/src/treeinterp/config_files/conditions.csv
  roboteam_ai/src/utilities/Constants.h
  roboteam_ai/src/utilities/GameStateManager.cpp
  roboteam_ai/src/utilities/StrategyManager.cpp
  roboteam_ai/src/utilities/StrategyManager.h
  roboteam_ai/test/UtilTests/RefereeTest.cpp
  roboteam_ai/test/UtilTests/StrategyManagerTest.cpp
Labels: Ready for review

#618 remove shotAtGoal condition for resuming normal Play
  roboteam_ai/src/conditions/ResumePlayAfterPenalty.cpp
Labels: Quick fix, Ready for review

#622 Feature/battery stats and refresh
  roboteam_ai/src/interface/widgets/MainControlsWidget.cpp
  roboteam_ai/src/interface/widgets/MainControlsWidget.h
  roboteam_ai/src/interface/widgets/widget.cpp
Labels: Ready for review, feature

#619 fixing some shootOut problems
  CMakeLists.txt
  roboteam_ai/src/Switches.cpp
  roboteam_ai/src/jsons/keeper/shootout_defend_tactic.json
  roboteam_ai/src/jsons/keeper/shootout_prepare_tactic.json
  roboteam_ai/src/jsons/keeper/shootout_shoot_tactic.json
  roboteam_ai/src/jsons/roles/shootout_defend_role.json
  roboteam_ai/src/jsons/roles/shootout_prepare_role.json
  roboteam_ai/src/jsons/roles/shootout_shoot_role.json
  roboteam_ai/src/skills/KickTo.cpp
  roboteam_ai/src/skills/KickTo.h
  roboteam_ai/src/treeinterp/config_files/skills.csv
Labels: Ready for review
