Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2020-02, with the labels that each got.

#782 Refactor/roboteam world optimize
  include/roboteam_ai/world_new/WorldData.hpp
  src/world_new/WorldData.cpp
  src/world_new/views/WorldDataView.cpp
  test/helpers/WorldHelper.cpp
  test/helpers/WorldHelper.h
Labels: Ready for merge

#786 fixed the insane spam from Field::get*
  src/interface/widgets/widget.cpp
Labels: Critical priority, Ready for merge, high priority

#788 Adde ccache support
  CMakeLists.txt
Labels: Ready for review

#790 Replaced hardcoded compiler path with the one found by CMake
  CMakeLists.txt
Labels: Quick fix

#793 New dribbler skill
  CMakeLists.txt
  include/roboteam_ai/new_skills/SetDribbler.h
  src/new_skills/SetDribbler.cpp
Labels: Ready for review, on hold for now

#801 Test kept hanging on while-loop in WorldHelper::getWorldMsg
  test/World_newTests/HistorySizeTest.cpp
Labels: Critical priority, Ready for merge

#805 Fixed missing header inclusion
  include/roboteam_ai/analysis/play-utilities/Play.h
Labels: Quick fix, Ready for merge

#767 Create the 'Dealer' class as a potential replacement for RobotDealer
  CMakeLists.txt
  include/roboteam_ai/utilities/Dealer.h
  include/roboteam_ai/world_new/Robot.hpp
  src/utilities/Dealer.cpp
  src/world_new/Robot.cpp
  src/world_new/WorldData.cpp
  test/UtilTests/DealerTest.cpp
  test/helpers/WorldHelper.cpp
  test/helpers/WorldHelper.h
  test/main.cpp
Labels: Ready for merge, enhancement

#802 cleanup iomanager
  include/roboteam_ai/ApplicationManager.h
  include/roboteam_ai/analysis/AnalysisReport.h
  include/roboteam_ai/analysis/GameAnalyzer.h
  include/roboteam_ai/coach/defence/DefencePositionCoach.h
  include/roboteam_ai/coach/defence/PossiblePass.h
  include/roboteam_ai/coach/heuristics/CoachHeuristics.h
  include/roboteam_ai/coach/heuristics/OffensiveScore.h
  include/roboteam_ai/control/BasicPosControl.h
  include/roboteam_ai/control/PosController.h
  include/roboteam_ai/control/ball-handling/BallHandlePosControl.h
  include/roboteam_ai/control/numtrees/NumTreePosControl.h
  include/roboteam_ai/control/shot-controllers/ShotController.h
  include/roboteam_ai/utilities/IOManager.h
  include/roboteam_ai/world/FieldComputations.h
  include/roboteam_ai/world/World.h
  include/roboteam_ai/world_new/World.hpp
  include/roboteam_ai/world_new/WorldData.hpp
  include/roboteam_ai/world_new/views/RobotView.hpp
  include/roboteam_ai/world_new/views/WorldDataView.hpp
  src/ApplicationManager.cpp
  src/analysis/AnalysisReport.cpp
  src/analysis/GameAnalyzer.cpp
  src/coach/OffensiveCoach.cpp
  src/coach/defence/DefenceDealer.cpp
  src/coach/defence/DefencePositionCoach.cpp
  src/coach/defence/PossiblePass.cpp
  src/coach/heuristics/CoachHeuristics.cpp
  src/coach/heuristics/OffensiveScore.cpp
  src/coach/heuristics/PassScore.cpp
  src/coach/midfield/MidFieldCoach.cpp
  src/conditions/HasClearShot.cpp
  src/control/ball-handling/BallHandlePosControl.cpp
  src/interface/widgets/RobotsWidget.cpp
  src/interface/widgets/mainWindow.cpp
  src/interface/widgets/widget.cpp
  src/roboteam_ai.cpp
  src/treeinterp/tactics/DefaultTactic.cpp
  src/utilities/IOManager.cpp
  src/world/FieldComputations.cpp
  src/world/World.cpp
  src/world_new/Ball.cpp
  src/world_new/Robot.cpp
  src/world_new/World.cpp
  src/world_new/WorldData.cpp
  src/world_new/views/RobotView.cpp
  src/world_new/views/WorldDataView.cpp
Labels: Ready for merge, refactor
