Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2020-01, with the labels that each got.

#715 Solve pass strictness problem
  src/coach/PassCoach.cpp
Labels: on hold for now

#752 New travis branch :)
  .travis.yml
  CMakeLists.txt
  src/skills/Keeper.cpp
Labels: Ready for merge

#755 fix .travis.yml
  .travis.yml
Labels: Ready for review

#759 add pid to utils and remove it from ai
  CMakeLists.txt
  include/roboteam_ai/control/PosController.h
  include/roboteam_ai/control/ballHandling/BallHandlePosControl.h
  include/roboteam_ai/control/pid.h
  src/control/pid.cpp
Labels: Waiting for other PR

#760 remove json from AI and use apt/brew json instead
  include/roboteam_ai/treeinterp/BTFactory.h
  include/roboteam_ai/treeinterp/JsonReader.h
  include/roboteam_ai/treeinterp/PropertiesParser.h
  include/roboteam_ai/treeinterp/TreeInterpreter.h
  include/roboteam_ai/treeinterp/json.h
  src/treeinterp/PropertiesParser.cpp
  src/treeinterp/TreeInterpreter.cpp
  test/UtilTests/PropertiesParserTest.cpp
Labels: Ready for review

#754 Move Hungarian algorithm to utils
  CMakeLists.txt
  include/roboteam_ai/control/Hungarian.h
  include/roboteam_ai/skills/formations/Formation.h
  include/roboteam_ai/skills/formations/KickOffUsFormation.h
  src/coach/OffensiveCoach.cpp
  src/control/Hungarian.cpp
  src/skills/formations/BallPlacementFormation.cpp
  src/skills/formations/DefendFreeKick.cpp
  src/skills/formations/Formation.cpp
  src/skills/formations/FreeKickFormation.cpp
  src/skills/formations/KickOffThemFormation.cpp
  src/skills/formations/KickOffUsFormation.cpp
  src/skills/formations/PenaltyFormation.cpp
  src/skills/formations/StopFormation.cpp
  src/skills/formations/TimeoutFormation.cpp
  test/ControlTests/HungarianTest.cpp
Labels: Ready for review

#775 Fix UB in worlddata.cpp for us and them vectors
  src/world_new/WorldData.cpp
Labels: Ready for merge, high priority
