Repository RoboTeamTwente/roboteam_ai, pull requests merged in 2020-03, with the labels that each got.

#824 Sensible GUI framerates
  include/roboteam_ai/interface/api/Input.h
  include/roboteam_ai/interface/widgets/TreeVisualizerWidget.h
  src/interface/api/Input.cpp
  src/interface/widgets/TreeVisualizerWidget.cpp
  src/interface/widgets/mainWindow.cpp
Labels: Ready for review, enhancement

#821 Feature/standardized prints
  include/roboteam_ai/ApplicationManager.h
  include/roboteam_ai/treeinterp/Leaf.h
  src/ApplicationManager.cpp
  src/bt/Blackboard.cpp
  src/bt/Node.cpp
  src/control/numtrees/NumTreePosControl.cpp
  src/interface/widgets/SettingsWidget.cpp
  src/manual/JoystickManager.cpp
  src/roboteam_ai.cpp
  src/skills/formations/BallPlacementFormation.cpp
  src/treeinterp/BTFactory.cpp
  src/treeinterp/Leaf.cpp
  src/utilities/Constants.cpp
  src/utilities/Dealer.cpp
  src/utilities/GameStateManager.cpp
  src/utilities/IOManager.cpp
  src/utilities/RefGameState.cpp
  src/utilities/RobotDealer.cpp
  src/utilities/Settings.cpp
  src/world/Ball.cpp
  src/world/World.cpp
Labels: Ready for review, feature, proposal

#827 move ccache to cmake modules
  CMakeLists.txt
  cmake_modules/ccache.cmake
  src/treeinterp/Leaf.cpp
Labels: Ready for merge

#861 Implemented rotate skill
  CMakeLists.txt
  include/roboteam_ai/stp/StpInfo.h
  include/roboteam_ai/stp/new_skills/Rotate.h
  src/stp/new_skills/Rotate.cpp
Labels: Skill

#854 Kick skill
  CMakeLists.txt
  include/roboteam_ai/stp/StpInfo.h
  include/roboteam_ai/stp/new_skills/Kick.h
  src/stp/new_skills/Kick.cpp
Labels: Skill

#867 Chip skill
  CMakeLists.txt
  include/roboteam_ai/stp/new_skills/Chip.h
  src/stp/new_skills/Chip.cpp
Labels: Skill

#893 Fix race condition
  src/interface/widgets/RobotsWidget.cpp
Labels: Ready for merge, Ready for review, bug

#897 stp receive tactic
  CMakeLists.txt
  include/roboteam_ai/stp/new_tactics/Receive.h
  src/stp/new_tactics/Receive.cpp
Labels: Tactic

#891 Feature/stp kick at pos tactic
  CMakeLists.txt
  include/roboteam_ai/stp/StpInfo.h
  include/roboteam_ai/stp/new_tactics/KickAtPos.h
  src/stp/new_plays/TestPlay.cpp
  src/stp/new_roles/TestRole.cpp
  src/stp/new_skills/Kick.cpp
  src/stp/new_skills/Rotate.cpp
  src/stp/new_tactics/KickAtPos.cpp
Labels: Ready for review

#892 Implemented ChipAtPos tactic
  CMakeLists.txt
  include/roboteam_ai/stp/new_tactics/ChipAtPos.h
  src/stp/new_plays/TestPlay.cpp
  src/stp/new_roles/TestRole.cpp
  src/stp/new_skills/Chip.cpp
  src/stp/new_tactics/ChipAtPos.cpp
Labels: Ready for review

#903 Feature/stp drive with ball tactic
  CMakeLists.txt
  include/roboteam_ai/stp/new_tactics/DriveWithBall.h
  src/stp/Skill.cpp
  src/stp/new_plays/TestPlay.cpp
  src/stp/new_tactics/BlockRobot.cpp
  src/stp/new_tactics/DriveWithBall.cpp
Labels: Ready for review

#908 Feature/stp role class
  include/roboteam_ai/stp/Role.hpp
  include/roboteam_ai/stp/new_roles/TestRole.h
  src/stp/Role.cpp
  src/stp/new_plays/TestPlay.cpp
  src/stp/new_roles/TestRole.cpp
Labels: Role

#912 Fixed a bug that caused some tests to randomly fail
  test/UtilTests/DealerTest.cpp
  test/UtilTests/RefereeTest.cpp
  test/World_newTests/WorldResetTests.cpp
  test/helpers/WorldHelper.cpp
Labels: Ready for review

#910 Stp intercept tactic
  CMakeLists.txt
  include/roboteam_ai/stp/new_tactics/Intercept.h
  src/stp/new_plays/TestPlay.cpp
  src/stp/new_roles/TestRole.cpp
  src/stp/new_tactics/Intercept.cpp
Labels: Ready for review, Tactic, on hold for now

#926 Tactic Pipeline Refactoring
  src/stp/Tactic.cpp
  test/StpTests/TacticTests.cpp
Labels: Tactic

#928 Feature/stp role clean up
  src/stp/Role.cpp
Labels: Role

#938 Better way for refreshing the views
  include/roboteam_ai/stp/Play.hpp
  src/stp/Play.cpp
Labels: Clean up

#954 Fix/stp improved kick chip speed
  include/roboteam_ai/stp/StpInfo.h
  include/roboteam_ai/utilities/Constants.h
  src/stp/new_plays/Pass.cpp
  src/stp/new_roles/TestRole.cpp
  src/stp/new_tactics/ChipAtPos.cpp
  src/stp/new_tactics/KickAtPos.cpp
  src/utilities/Constants.cpp
Labels: Clean up, Ready for review

#969 Fixed bug std::out_of_range when a controller disconnects
  src/manual/JoystickManager.cpp
Labels: Quick fix, Ready for merge, Ready for review

#966 Added ballSensor input to hasBall
  include/roboteam_ai/stp/new_constants/ControlConstants.h
  include/roboteam_ai/world_new/Robot.hpp
  include/roboteam_ai/world_new/views/RobotView.hpp
  src/stp/Role.cpp
  src/stp/new_constants/ControlConstants.cpp
  src/stp/new_skills/Chip.cpp
  src/stp/new_skills/GoToPos.cpp
  src/stp/new_skills/Kick.cpp
  src/stp/new_tactics/ChipAtPos.cpp
  src/stp/new_tactics/KickAtPos.cpp
  src/world_new/Robot.cpp
  src/world_new/views/RobotView.cpp
Labels: Ready for review

#983 Default initialize these vars to fix UB
  include/roboteam_ai/world_new/Robot.hpp
Labels: Ready for review

#973 Removed initialize call from tactic and role ctors
  src/stp/new_plays/Halt.cpp
  src/stp/new_roles/Halt.cpp
  src/stp/new_roles/PassReceiver.cpp
  src/stp/new_roles/Passer.cpp
  src/stp/new_roles/TestRole.cpp
  src/stp/new_tactics/BlockRobot.cpp
  src/stp/new_tactics/ChipAtPos.cpp
  src/stp/new_tactics/DriveWithBall.cpp
  src/stp/new_tactics/GetBall.cpp
  src/stp/new_tactics/Halt.cpp
  src/stp/new_tactics/Intercept.cpp
  src/stp/new_tactics/KickAtPos.cpp
  src/stp/new_tactics/Receive.cpp
  src/stp/new_tactics/TestTactic.cpp
Labels: Ready for merge

#975 Implemented the Harasser role
  CMakeLists.txt
  include/roboteam_ai/stp/new_roles/Harasser.h
  src/stp/new_roles/Harasser.cpp
Labels: Role
